name: Release

on:
  workflow_dispatch:
    inputs:
      options:
        description:
          Addional arguments send to nx release, if empty uses conventional-commits.
          https://nx.dev/nx-api/nx/documents/release
        type: string
        required: false

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          filter: tree:0
          fetch-depth: 0
      - uses: actions/setup-node@v5
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - run: npm ci --legacy-peer-deps
      - name: Nx publish
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
          npx nx release ${{ github.event.inputs.options }}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
